export default [
    {
        code: '516002',
        key: 'queryChartIndexConfig',
        url: '/oprnintg/v1/queryChartIndexConfig',
        dis: '查询图表指标配置',
    },
    {
        code: '516001',
        key: 'queryModuleChartConfig',
        url: '/oprnintg/v1/queryModuleChartConfig',
        dis: '查询模块图表配置',
    },
    {
        code: '516003',
        key: 'queryChartIndexData',
        url: '/oprnintg/v1/queryChartIndexData ',
        dis: '查询图表指标数据',
    },
    {
        code: '516004',
        key: 'queryOptIdxState',
        url: '/oprnintg/v1/queryOptIdxState',
        dis: '查询运作类指标状态',
    },
    {
        code: '516005',
        key: 'queryOptIdxStateStat',
        url: '/oprnintg/v1/queryOptIdxStateStat',
        dis: '查询运作类指标状态统计',
    },
    {
        code: '516006',
        key: 'queryErrOrImpRpt',
        url: '/oprnintg/v1/queryErrOrImpRpt',
        dis: '重大事项查询',
    },
    {
        code: '516008',
        key: 'queryESB',
        url: '/oprnintg/v1/queryESB',
        dis: 'ESB对接集中运营接口',
    },
    {
        code: '516009',
        key: 'queryDW',
        url: '/oprnintg/v1/queryDW',
        dis: '数仓数据实时查询接口',
    },
    {
        code: '516007',
        key: 'queryErrOrImpRptStat',
        url: '/oprnintg/v1/queryErrOrImpRptStat',
        dis: '重大事项统计查询',
    },
    {
        code: '516012',
        key: 'queryCallInfo',
        url: '/oprnintg/v1/queryCallInfo',
        dis: '呼叫中心数据实时查询接口',
    },
    {
        code: '',
        key: 'queryWK',
        url: '/oprnintg/v1/queryWK',
        dis: '呼叫中心网开查询接口',
    },
    {
        code: '516015',
        key: 'queryBaseDblcs',
        url: '/oprnintg/v1/queryBaseDblcs ',
        dis: '获取代办流程数',
    },
    {
        code: '516014',
        key: 'querySyTzgg',
        url: '/oprnintg/v1/querySyTzgg',
        dis: '获取通知公告',
    },
    {
        code: '516017',
        key: 'queryBaseNewClass',
        url: '/oprnintg/v1/queryBaseNewClass',
        dis: '获取新闻类型',
    },
    {
        code: '516018',
        key: 'querySyCycz',
        url: '/oprnintg/v1/querySyCycz',
        dis: '获取常用操作',
    },
    // {
    //     code: '516019',
    //     key: 'queryJyrHk',
    //     url: '/oprnintg/v1/queryJyrHk',
    //     dis: '是否香港交易日',
    // },
    {
        code: '516020',
        key: 'queryAccountProperty',
        url: '/oprnintg/v1/queryAccountProperty',
        dis: '期货-未规范客户数实时查询接口',
    },
    {
        code: '',
        key: 'queryScreenPermission',
        url: '/oprnintg/v1/queryScreenPermission',
        dis: '查询用户监控屏权限',
    },
    {
        code: '',
        key: 'getRiskIndexTaskMon',
        url: '/oprnintg/v1/getRiskIndexTaskMon',
        dis: '查询风险提示',
    },
    {
        code: '',
        key: 'queryUnfinishTargetList',
        url: '/oprnintg/v1/queryUnfinishTargetList',
        dis: '查询主屏未完成指标列表',
    },
    {
        code: '',
        key: 'queryBranUserSettings',
        url: '/oprnintg/v1/queryBranUserSettings',
        dis: '查询配置信息存储',
    },
    {
        code: '',
        key: 'addBranSetting',
        url: '/oprnintg/v1/addBranSetting',
        dis: '保存分公司配置信息',
    },
    {
        code: '',
        key: 'queryBranSetting',
        url: '/oprnintg/v1/queryBranSetting',
        dis: '配置信息查询',
    },
];
