export default [
  {code: '', key: 'queryLiftcycleMilestone', url: '/projectManage/queryLiftcycleMilestone', dis: '查询生命周期里程碑执行情况'},
  {code: '', key: 'queryLifecycleStuff', url: '/projectManage/queryLifecycleStuff', dis: '查询生命周期里程碑中的事项执行情况'},
  {code: '', key: 'queryOwnerWorkflow', url: '/projectManage/queryOwnerWorkflow', dis: '查询登录用户发起的流程情况'},
  {code: '', key: 'queryOwnerProjectList', url: '/projectManage/queryOwnerProjectList', dis: '查询当前登录用户的项目列表，查询下拉框用'},
  {code: '', key: 'queryOwnerMessage', url: '/projectManage/queryOwnerMessage', dis: '查询当前登录用户的消息列表'},
  {code: '', key: 'createOperateHyperLink', url: '/projectManage/v1/createOperateHyperLink', dis: '获取livebos加密url'},
  {code: '', key: 'updateMessageState', url: '/projectManage/updateMessageState', dis: '将待办事项的查看状态修改为已读'},
  {code: '', key: 'queryProjectInfoInCycle', url: '/projectManage/queryProjectInfoInCycle', dis: '查询生命周期用到的项目信息'},
  {code: '', key: 'queryHTXXByXQTC', url: '/projectManage/queryHTXXByXQTC', dis: '查询合同信息修改弹窗需要的合同信息'},
  {code: '', key: 'updateHTXX', url: '/projectManage/updateHTXX', dis: '更新合同信息'},
  {code: '', key: 'queryOAUrl', url: '/projectManage/queryOAUrl', dis: '查询OAUrl'},
  {code: '', key: 'queryWpsWDXX', url: '/projectManage/queryWpsWDXX', dis: '查询预览所需的Url'},
  {code: '', key: 'queryZBXXByXQTC', url: '/projectManage/queryZBXXByXQTC', dis: '查询招标信息修改弹窗需要的招标信息'},
  {code: '', key: 'queryGysInZbxx', url: '/projectManage/queryGysInZbxx', dis: '查询招标信息修改时的供应商下拉列表'},
  {code: '', key: 'updateZbxx', url: '/projectManage/UpdateTenderInformation', dis: '更新招标信息'},
];
