export default [
  {
    code: '',
    key: 'queryLiftcycleMilestone',
    url: '/projectManage/queryLiftcycleMilestone',
    dis: '查询生命周期里程碑执行情况',
  },
  {
    code: '',
    key: 'queryLifecycleStuff',
    url: '/projectManage/queryLifecycleStuff',
    dis: '查询生命周期里程碑中的事项执行情况',
  },
  {
    code: '',
    key: 'queryOwnerWorkflow',
    url: '/projectManage/queryOwnerWorkflow',
    dis: '查询登录用户发起的流程情况',
  },
  {
    code: '',
    key: 'queryOwnerProjectList',
    url: '/projectManage/queryOwnerProjectList',
    dis: '查询当前登录用户的项目列表，查询下拉框用',
  },
  {
    code: '',
    key: 'queryOwnerMessage',
    url: '/projectManage/queryOwnerMessage',
    dis: '查询当前登录用户的消息列表',
  },
  {
    code: '',
    key: 'createOperateHyperLink',
    url: '/projectManage/v1/createOperateHyperLink',
    dis: '获取livebos加密url',
  },
  {
    code: '',
    key: 'updateMessageState',
    url: '/projectManage/updateMessageState',
    dis: '将待办事项的查看状态修改为已读',
  },
  {
    code: '',
    key: 'queryProjectInfoInCycle',
    url: '/projectManage/queryProjectInfoInCycle',
    dis: '查询生命周期用到的项目信息',
  },
  {
    code: '',
    key: 'queryHTXXByXQTC',
    url: '/projectManage/queryHTXXByXQTC',
    dis: '查询合同信息修改弹窗需要的合同信息',
  },
  { code: '', key: 'updateHTXX', url: '/projectManage/updateHTXX', dis: '更新合同信息' },
  { code: '', key: 'queryOAUrl', url: '/projectManage/queryOAUrl', dis: '查询OAUrl' },
  { code: '', key: 'queryWpsWDXX', url: '/projectManage/queryWpsWDXX', dis: '查询预览所需的Url' },
  {
    code: '',
    key: 'zipLivebosFilesPost',
    url: '/projectManage/zipLivebosFilesPost',
    dis: '查询预览所需的Url',
  },
  { code: '', key: 'queryZBYSFJ', url: '/projectManage/queryZBYSFJ', dis: 'zip文件下载' },
  {
    code: '',
    key: 'queryZBXXByXQTC',
    url: '/projectManage/queryZBXXByXQTC',
    dis: '查询中标信息修改弹窗需要的中标信息',
  },
  {
    code: '',
    key: 'queryGysInZbxx',
    url: '/projectManage/queryGysInZbxx',
    dis: '查询中标信息修改时的供应商下拉列表',
  },
  {
    code: '',
    key: 'updateZbxx',
    url: '/projectManage/UpdateTenderInformation',
    dis: '更新中标信息',
  },
  {
    code: '',
    key: 'exportExcel',
    url: '/projectManage/v1/CapitalBudgetExportExcel',
    dis: '资本性年初预算汇总导出EXCEL',
  },
  {
    code: '',
    key: 'queryEpibolyLifeCycleExeStatue',
    url: '/projectManage/QueryEpibolyLifeCycleExeStatue',
    dis: '查询外包事务生命周期执行情况',
  },
  {
    code: '',
    key: 'queryDigitalSpecialClassWeeklyReport',
    url: '/projectManage/QueryDigitalSpecialClassWeeklyReport',
    dis: '查询新数字化专班周报',
  },
  {
    code: '',
    key: 'operateSZHZBWeekly',
    url: '/projectManage/operateSZHZBWeekly',
    dis: '更新、退回、删除、跳过本周数字化专班周报信息',
  },
  {
    code: '',
    key: 'operateMonthly',
    url: '/projectManage/operateMonthly',
    dis: '更新、退回、删除月报信息',
  },
  {
    code: '',
    key: 'queryMonthlyList',
    url: '/projectManage/queryMonthlyList',
    dis: '查询月报信息',
  },
  {
    code: '',
    key: 'digitalSpecialClassWeeklyReportExcel',
    url: '/projectManage/v1/DigitalSpecialClassWeeklyReportExcel',
    dis: '数字化专班周报导出EXCELL',
  },
  {
    code: '',
    key: 'digitalSpecialClassMonthReportExcel',
    url: '/projectManage/v1/DigitalSpecialClassMonthReportExcel',
    dis: '数字化专班月报导出EXCELL',
  },
  {
    code: '',
    key: 'queryUserInfo',
    url: '/projectManage/queryUserInfo',
    dis: '数字化专班月报查询用户信息,填报人下拉列表使用',
  },
  {
    code: '',
    key: 'queryPaymentAccountList',
    url: '/projectManage/queryPaymentAccountList',
    dis: '查询收款账户',
  },
  {
    code: '',
    key: 'queryPaymentFlowInfo',
    url: '/EKB/v1/queryPaymentFlowInfo',
    dis: '创建单据时获取基本信息',
  },
  {
    code: '',
    key: 'queryPaymentFlowDetail',
    url: '/EKB/v1/queryPaymentFlowDetail',
    dis: '创建单据时获取费用明细',
  },
  { code: '', key: 'creatPaymentFlow', url: '/EKB/v1/creatPaymentFlow', dis: '创建单据' },
  {
    code: '',
    key: 'queryPaymentFlowDetailFile',
    url: '/EKB/v1/queryPaymentFlowDetailFile',
    dis: '查询费用明细预览时需要的文档信息',
  },
  {
    code: '',
    key: 'getApplyListProvisionalAuth',
    url: '/EKB/v1/getApplyListProvisionalAuth',
    dis: '获取预览付款单的url',
  },
  {
    code: '',
    key: 'getStreamByLiveBos',
    url: '/EKB/v1/getStreamByLiveBos',
    dis: '获取LiveBos文档流',
  },
  {
    code: '',
    key: 'queryContrastStatisticInfo',
    url: '/projectManage/queryContrastStatisticInfo',
    dis: '查询领导看板页顶部较去年数据',
  },
  { code: '', key: 'checkInvoice', url: '/EKB/v1/checkInvoice', dis: '对接易快报发票查验接口' },
  { code: '', key: 'queryUserRole', url: '/projectManage/queryUserRole', dis: '查询用户的角色' },
  {
    code: '',
    key: 'queryAttachLibraryList',
    url: '/projectManage/queryAttachLibraryList',
    dis: '查询文档列表',
  },
  {
    code: '',
    key: 'queryHistoryAttach',
    url: '/projectManage/queryHistoryAttach',
    dis: '查询历史文档',
  },
  { code: '', key: 'queryFileStream', url: '/projectManage/v1/queryFileStream', dis: '下载文件' },
  {
    code: '',
    key: 'zipLivebosFilesRowsPost',
    url: '/projectManage/zipLivebosFilesRowsPost',
    dis: '下载文件(压缩)',
  },
  {
    code: '',
    key: 'individuationGetOAResult',
    url: '/ZSZQ/v1/individuationGetOAResult',
    dis: '个性化页面发起流程到oa',
  },
  {
    code: '',
    key: 'queryHjgWeeklyInfo',
    url: '/projectManage/queryHjgWeeklyInfo',
    dis: '获取汇金谷零售周报汇总信息',
  },
  {
    code: '',
    key: 'operateHjgWeeklyReport',
    url: '/projectManage/operateHjgWeeklyReport',
    dis: '更新、提交、删除、跳过周报信息',
  },
  {
    code: '',
    key: 'hJGWeeklyReportExcel',
    url: '/projectManage/v1/HJGWeeklyReportExcel',
    dis: '导出数字化专班周报excel',
  },
  {
    code: '',
    key: 'queryOafilerela',
    url: '/ZSZQ/v1/queryOafilerela',
    dis: '调用oa接口获取关联文件',
  },
  {
    code: '',
    key: 'queryProjectListInfo',
    url: '/projectManage/v1/queryProjectListInfo',
    dis: '查询项目信息列表的项目信息',
  },
  {
    code: '',
    key: 'queryProjectListPara',
    url: '/projectManage/v1/queryProjectListPara',
    dis: '查询项目信息列表的查询条件',
  },
  {
    code: '',
    key: 'queryProjectInfoAll',
    url: '/projectManage/v1/queryProjectInfoAll',
    dis: '查询项目信息所有基本信息',
  },
  {
    code: '',
    key: 'queryXWHYAFJ',
    url: '/projectManage/queryXWHYAFJ',
    dis: '查询要导出的信委会议案',
  },
  {
    code: '',
    key: 'queryStagingOverviewInfo',
    url: '/projectManage/queryStagingOverviewInfo',
    dis: '查询工作台的零散信息',
  },
  {
    code: '',
    key: 'queryBudgetOverviewInfo',
    url: '/projectManage/queryBudgetOverviewInfo',
    dis: '查询预算概览信息',
  },
  {
    code: '',
    key: 'queryMemberOverviewInfo',
    url: '/projectManage/queryMemberOverviewInfo',
    dis: '查询人员概览信息',
  },
  {
    code: '',
    key: 'querySupplierOverviewInfo',
    url: '/projectManage/querySupplierOverviewInfo',
    dis: '查询供应商信息',
  },
  {
    code: '',
    key: 'queryProjectGeneralInfo',
    url: '/projectManage/queryProjectGeneralInfo',
    dis: '查询首页项目综合信息',
  },
  {
    code: '',
    key: 'queryCreatePaymentInfo',
    url: '/EKB/v1/queryCreatePaymentInfo',
    dis: '查询发起付款流程所需的基本信息',
  },
  {
    code: '',
    key: 'queryMemberDetailInfo',
    url: '/projectManage/queryMemberDetailInfo',
    dis: '查询人员详情信息',
  },
  {
    code: '',
    key: 'queryLabelDetailInfo',
    url: '/projectManage/queryLabelDetailInfo',
    dis: '查询标签详情信息',
  },
  {
    code: '',
    key: 'updateProjectOtherInfo',
    url: '/projectManage/updateProjectOtherInfo',
    dis: '查询标签详情信息',
  },
  {
    code: '',
    key: 'queryProjectMessages',
    url: '/projectManage/queryProjectMessages',
    dis: '查询项目留言',
  },
  {
    code: '',
    key: 'updateProjectMessages',
    url: '/projectManage/updateProjectMessages',
    dis: '新增、修改项目留言',
  },
  {
    code: '',
    key: 'querySupplierList',
    url: '/projectManage/querySupplierList',
    dis: '查询供应商信息列表',
  },
  {
    code: '',
    key: 'queryZCXX',
    url: '/projectManage/queryZCXX',
    dis: '查询招采购信息',
  },
  {
    code: '',
    key: 'querySupplierDetailInfo',
    url: '/projectManage/querySupplierDetailInfo',
    dis: '查询供应商详情',
  },
  {
    code: '',
    key: 'operateSupplierInfo',
    url: '/projectManage/operateSupplierInfo',
    dis: '编辑供应商详情',
  },
  {
    code: '',
    key: 'queryMemberInfo',
    url: '/projectManage/queryMemberInfo',
    dis: '查询人员信息',
  },
  {
    code: '',
    key: 'remindSubProjectFinish',
    url: '/projectManage/remindSubProjectFinish',
    dis: '提醒子项目完善信息',
  },
  {
    code: '',
    key: 'operateOutsourceRequirements',
    url: '/projectManage/operateOutsourceRequirements',
    dis: '需求发起',
  },
  {
    code: '',
    key: 'queryOutsourceRequirement',
    url: '/projectManage/queryOutsourceRequirement',
    dis: '查询需求发起结果',
  },
  {
    code: '',
    key: 'queryOutsourceRequirementList',
    url: '/projectManage/queryOutsourceRequirementList',
    dis: '查询外包需求列表',
  },
  {
    code: '',
    key: 'queryRequirementDetail',
    url: '/projectManage/queryRequirementDetail',
    dis: '查询人力外包需求详情',
  },
  {
    code: '',
    key: 'queryRequirementListPara',
    url: '/projectManage/queryRequirementListPara',
    dis: '外包人员列表查询条件',
  },
  {
    code: '',
    key: 'queryWeekday',
    url: '/projectManage/queryWeekday',
    dis: '查询工作日',
  },
  {
    code: '',
    key: 'operateEvaluation',
    url: '/projectManage/operateEvaluation',
    dis: '综合评测信息操作',
  },
  {
    code: '',
    key: 'queryOutsourceMemberList',
    url: '/projectManage/queryOutsourceMemberList',
    dis: '查询人员信息',
  },
  {
    code: '',
    key: 'sendMail',
    url: '/projectManage/sendMail',
    dis: '邮件发送',
  },
  {
    code: '',
    key: 'resumeDistribution',
    url: '/projectManage/resumeDistribution',
    dis: '简历分发',
  },
  {
    code: '',
    key: 'queryOutsourceMemberDetail',
    url: '/projectManage/queryOutsourceMemberDetail',
    dis: '外包人员详情',
  },
  {
    code: '',
    key: 'queryEmail',
    url: '/projectManage/queryEmail',
    dis: '查询邮箱发件人信息',
  },
  {
    code: '',
    key: 'updateOutsourceMemberInfo',
    url: '/projectManage/updateOutsourceMemberInfo',
    dis: '外包人员信息编辑',
  },
  {
    code: '',
    key: 'queryEvaluationGradeInfo',
    url: '/projectManage/queryEvaluationGradeInfo',
    dis: '查询综合评测打分信息',
  },
  {
    code: '',
    key: 'evaluationScoring',
    url: '/projectManage/evaluationScoring',
    dis: '综合评测打分',
  },
  {
    code: '',
    key: 'supplierQueryDemand',
    url: '/projectManage/supplierQueryDemand',
    dis: '查询供应商需求',
  },
  {
    code: '',
    key: 'queryOutsourceCostList',
    url: '/projectManage/queryOutsourceCostList',
    dis: '查询费用列表',
  },
  {
    code: '',
    key: 'globalSearch',
    url: '/projectManage/globalSearch',
    dis: '全局搜索',
  },
  {
    code: '',
    key: 'outsourceCostCalculation',
    url: '/projectManage/outsourceCostCalculation',
    dis: '费用计算',
  },
  {
    code: '',
    key: 'uploadCurriculumVitae',
    url: '/projectManage/uploadCurriculumVitae',
    dis: '简历上传',
  },
  {
    code: '',
    key: 'costCalculationCheck',
    url: '/projectManage/costCalculationCheck',
    dis: '费用计算前校验',
  },
  {
    code: '',
    key: 'outsourceCostExportExcel',
    url: '/projectManage/outsourceCostExportExcel',
    dis: '外包费用导出Excel',
  },
  {
    code: '',
    key: 'queryOutsourceMemberAttendance',
    url: '/projectManage/queryOutsourceMemberAttendance',
    dis: '考勤查询',
  },
];
