export default [
  {
    code: '',
    key: 'queryLiftcycleMilestone',
    url: '/projectManage/queryLiftcycleMilestone',
    dis: '查询生命周期里程碑执行情况',
  },
  {
    code: '',
    key: 'queryLifecycleStuff',
    url: '/projectManage/queryLifecycleStuff',
    dis: '查询生命周期里程碑中的事项执行情况',
  },
  {
    code: '',
    key: 'queryOwnerWorkflow',
    url: '/projectManage/queryOwnerWorkflow',
    dis: '查询登录用户发起的流程情况',
  },
  {
    code: '',
    key: 'queryOwnerProjectList',
    url: '/projectManage/queryOwnerProjectList',
    dis: '查询当前登录用户的项目列表，查询下拉框用',
  },
  {
    code: '',
    key: 'queryOwnerMessage',
    url: '/projectManage/queryOwnerMessage',
    dis: '查询当前登录用户的消息列表',
  },
  {
    code: '',
    key: 'createOperateHyperLink',
    url: '/projectManage/v1/createOperateHyperLink',
    dis: '获取livebos加密url',
  },
  {
    code: '',
    key: 'updateMessageState',
    url: '/projectManage/updateMessageState',
    dis: '将待办事项的查看状态修改为已读',
  },
  {
    code: '',
    key: 'queryProjectInfoInCycle',
    url: '/projectManage/queryProjectInfoInCycle',
    dis: '查询生命周期用到的项目信息',
  },
  {
    code: '',
    key: 'queryHTXXByXQTC',
    url: '/projectManage/queryHTXXByXQTC',
    dis: '查询合同信息修改弹窗需要的合同信息',
  },
  { code: '', key: 'updateHTXX', url: '/projectManage/updateHTXX', dis: '更新合同信息' },
  { code: '', key: 'queryOAUrl', url: '/projectManage/queryOAUrl', dis: '查询OAUrl' },
  { code: '', key: 'queryWpsWDXX', url: '/projectManage/queryWpsWDXX', dis: '查询预览所需的Url' },
  {
    code: '',
    key: 'zipLivebosFilesPost',
    url: '/projectManage/zipLivebosFilesPost',
    dis: '查询预览所需的Url',
  },
  { code: '', key: 'queryZBYSFJ', url: '/projectManage/queryZBYSFJ', dis: 'zip文件下载' },
  {
    code: '',
    key: 'queryZBXXByXQTC',
    url: '/projectManage/queryZBXXByXQTC',
    dis: '查询中标信息修改弹窗需要的中标信息',
  },
  {
    code: '',
    key: 'queryGysInZbxx',
    url: '/projectManage/queryGysInZbxx',
    dis: '查询中标信息修改时的供应商下拉列表',
  },
  {
    code: '',
    key: 'updateZbxx',
    url: '/projectManage/UpdateTenderInformation',
    dis: '更新中标信息',
  },
  {
    code: '',
    key: 'exportExcel',
    url: '/projectManage/v1/CapitalBudgetExportExcel',
    dis: '资本性年初预算汇总导出EXCEL',
  },
  {
    code: '',
    key: 'queryEpibolyLifeCycleExeStatue',
    url: '/projectManage/QueryEpibolyLifeCycleExeStatue',
    dis: '查询外包事务生命周期执行情况',
  },
  {
    code: '',
    key: 'queryDigitalSpecialClassWeeklyReport',
    url: '/projectManage/QueryDigitalSpecialClassWeeklyReport',
    dis: '查询新数字化专班周报',
  },
  {
    code: '',
    key: 'operateSZHZBWeekly',
    url: '/projectManage/operateSZHZBWeekly',
    dis: '更新、退回、删除、跳过本周数字化专班周报信息',
  },
  {
    code: '',
    key: 'operateMonthly',
    url: '/projectManage/operateMonthly',
    dis: '更新、退回、删除月报信息',
  },
  {
    code: '',
    key: 'queryMonthlyList',
    url: '/projectManage/queryMonthlyList',
    dis: '查询月报信息',
  },
  {
    code: '',
    key: 'digitalSpecialClassWeeklyReportExcel',
    url: '/projectManage/v1/DigitalSpecialClassWeeklyReportExcel',
    dis: '数字化专班周报导出EXCELL',
  },
  {
    code: '',
    key: 'digitalSpecialClassMonthReportExcel',
    url: '/projectManage/v1/DigitalSpecialClassMonthReportExcel',
    dis: '数字化专班月报导出EXCELL',
  },
  {
    code: '',
    key: 'queryUserInfo',
    url: '/projectManage/queryUserInfo',
    dis: '数字化专班月报查询用户信息,填报人下拉列表使用',
  },
  {
    code: '',
    key: 'queryPaymentAccountList',
    url: '/projectManage/queryPaymentAccountList',
    dis: '查询收款账户',
  },
  {
    code: '',
    key: 'queryPaymentFlowInfo',
    url: '/EKB/v1/queryPaymentFlowInfo',
    dis: '创建单据时获取基本信息',
  },
  {
    code: '',
    key: 'queryPaymentFlowDetail',
    url: '/EKB/v1/queryPaymentFlowDetail',
    dis: '创建单据时获取费用明细',
  },
  { code: '', key: 'creatPaymentFlow', url: '/EKB/v1/creatPaymentFlow', dis: '创建单据' },
  {
    code: '',
    key: 'queryPaymentFlowDetailFile',
    url: '/EKB/v1/queryPaymentFlowDetailFile',
    dis: '查询费用明细预览时需要的文档信息',
  },
  {
    code: '',
    key: 'getApplyListProvisionalAuth',
    url: '/EKB/v1/getApplyListProvisionalAuth',
    dis: '获取预览付款单的url',
  },
  {
    code: '',
    key: 'getStreamByLiveBos',
    url: '/EKB/v1/getStreamByLiveBos',
    dis: '获取LiveBos文档流',
  },
  {
    code: '',
    key: 'queryContrastStatisticInfo',
    url: '/projectManage/queryContrastStatisticInfo',
    dis: '查询领导看板页顶部较去年数据',
  },
  { code: '', key: 'checkInvoice', url: '/EKB/v1/checkInvoice', dis: '对接易快报发票查验接口' },
  { code: '', key: 'queryUserRole', url: '/projectManage/queryUserRole', dis: '查询用户的角色' },
  {
    code: '',
    key: 'queryAttachLibraryList',
    url: '/projectManage/queryAttachLibraryList',
    dis: '查询文档列表',
  },
  {
    code: '',
    key: 'queryHistoryAttach',
    url: '/projectManage/queryHistoryAttach',
    dis: '查询历史文档',
  },
  { code: '', key: 'queryFileStream', url: '/projectManage/v1/queryFileStream', dis: '下载文件' },
  {
    code: '',
    key: 'zipLivebosFilesRowsPost',
    url: '/projectManage/zipLivebosFilesRowsPost',
    dis: '下载文件(压缩)',
  },
  {
    code: '',
    key: 'individuationGetOAResult',
    url: '/ZSZQ/v1/individuationGetOAResult',
    dis: '个性化页面发起流程到oa',
  },
  {
    code: '',
    key: 'queryHjgWeeklyInfo',
    url: '/projectManage/queryHjgWeeklyInfo',
    dis: '获取汇金谷零售周报汇总信息',
  },
  {
    code: '',
    key: 'operateHjgWeeklyReport',
    url: '/projectManage/operateHjgWeeklyReport',
    dis: '更新、提交、删除、跳过周报信息',
  },
  {
    code: '',
    key: 'hJGWeeklyReportExcel',
    url: '/projectManage/v1/HJGWeeklyReportExcel',
    dis: '导出数字化专班周报excel',
  },
  {
    code: '',
    key: 'queryOafilerela',
    url: '/ZSZQ/v1/queryOafilerela',
    dis: '调用oa接口获取关联文件',
  },
  {
    code: '',
    key: 'queryProjectListInfo',
    url: '/projectManage/v1/queryProjectListInfo',
    dis: '查询项目信息列表的项目信息',
  },
  {
    code: '',
    key: 'queryProjectListPara',
    url: '/projectManage/v1/queryProjectListPara',
    dis: '查询项目信息列表的查询条件',
  },
  {
    code: '',
    key: 'queryProjectInfoAll',
    url: '/projectManage/v1/queryProjectInfoAll',
    dis: '查询项目信息所有基本信息',
  },
  {
    code: '',
    key: 'queryXWHYAFJ',
    url: '/projectManage/queryXWHYAFJ',
    dis: '查询要导出的信委会议案',
  },
  {
    code: '',
    key: 'queryStagingOverviewInfo',
    url: '/projectManage/queryStagingOverviewInfo',
    dis: '查询工作台的零散信息',
  },
  {
    code: '',
    key: 'queryBudgetOverviewInfo',
    url: '/projectManage/queryBudgetOverviewInfo',
    dis: '查询预算概览信息',
  },
  {
    code: '',
    key: 'queryMemberOverviewInfo',
    url: '/projectManage/queryMemberOverviewInfo',
    dis: '查询人员概览信息',
  },
  {
    code: '',
    key: 'querySupplierOverviewInfo',
    url: '/projectManage/querySupplierOverviewInfo',
    dis: '查询供应商信息',
  },
  {
    code: '',
    key: 'queryProjectGeneralInfo',
    url: '/projectManage/queryProjectGeneralInfo',
    dis: '查询首页项目综合信息',
  },
  {
    code: '',
    key: 'queryCreatePaymentInfo',
    url: '/EKB/v1/queryCreatePaymentInfo',
    dis: '查询发起付款流程所需的基本信息',
  },
  {
    code: '',
    key: 'queryMemberDetailInfo',
    url: '/projectManage/queryMemberDetailInfo',
    dis: '查询人员详情信息',
  },
  {
    code: '',
    key: 'queryLabelDetailInfo',
    url: '/projectManage/queryLabelDetailInfo',
    dis: '查询标签详情信息',
  },
  {
    code: '',
    key: 'updateProjectOtherInfo',
    url: '/projectManage/updateProjectOtherInfo',
    dis: '查询标签详情信息',
  },
  {
    code: '',
    key: 'queryProjectMessages',
    url: '/projectManage/queryProjectMessages',
    dis: '查询项目留言',
  },
  {
    code: '',
    key: 'updateProjectMessages',
    url: '/projectManage/updateProjectMessages',
    dis: '新增、修改项目留言',
  },
  {
    code: '',
    key: 'querySupplierList',
    url: '/projectManage/querySupplierList',
    dis: '查询供应商信息列表',
  },
  {
    code: '',
    key: 'queryZCXX',
    url: '/projectManage/queryZCXX',
    dis: '查询招采购信息',
  },
  {
    code: '',
    key: 'querySupplierDetailInfo',
    url: '/projectManage/querySupplierDetailInfo',
    dis: '查询供应商详情',
  },
  {
    code: '',
    key: 'operateSupplierInfo',
    url: '/projectManage/operateSupplierInfo',
    dis: '编辑供应商详情',
  },
  {
    code: '',
    key: 'queryMemberInfo',
    url: '/projectManage/queryMemberInfo',
    dis: '查询人员信息',
  },
  {
    code: '',
    key: 'remindSubProjectFinish',
    url: '/projectManage/remindSubProjectFinish',
    dis: '提醒子项目完善信息',
  },
  {
    code: '',
    key: 'operateOutsourceRequirements',
    url: '/projectManage/operateOutsourceRequirements',
    dis: '需求发起',
  },
  {
    code: '',
    key: 'queryOutsourceRequirement',
    url: '/projectManage/queryOutsourceRequirement',
    dis: '查询需求发起结果',
  },
  {
    code: '',
    key: 'queryOutsourceRequirementList',
    url: '/projectManage/queryOutsourceRequirementList',
    dis: '查询外包需求列表',
  },
  {
    code: '',
    key: 'queryRequirementDetail',
    url: '/projectManage/queryRequirementDetail',
    dis: '查询人力外包需求详情',
  },
  {
    code: '',
    key: 'queryRequirementListPara',
    url: '/projectManage/queryRequirementListPara',
    dis: '外包人员列表查询条件',
  },
  {
    code: '',
    key: 'queryWeekday',
    url: '/projectManage/queryWeekday',
    dis: '查询工作日',
  },
  {
    code: '',
    key: 'operateEvaluation',
    url: '/projectManage/operateEvaluation',
    dis: '综合评测信息操作',
  },
  {
    code: '',
    key: 'queryOutsourceMemberList',
    url: '/projectManage/queryOutsourceMemberList',
    dis: '查询人员信息',
  },
  {
    code: '',
    key: 'sendMail',
    url: '/projectManage/sendMail',
    dis: '邮件发送',
  },
  {
    code: '',
    key: 'resumeDistribution',
    url: '/projectManage/resumeDistribution',
    dis: '简历分发',
  },
  {
    code: '',
    key: 'queryOutsourceMemberDetail',
    url: '/projectManage/queryOutsourceMemberDetail',
    dis: '外包人员详情',
  },
  {
    code: '',
    key: 'queryEmail',
    url: '/projectManage/queryEmail',
    dis: '查询邮箱发件人信息',
  },
  {
    code: '',
    key: 'updateOutsourceMemberInfo',
    url: '/projectManage/updateOutsourceMemberInfo',
    dis: '外包人员信息编辑',
  },
  {
    code: '',
    key: 'queryEvaluationGradeInfo',
    url: '/projectManage/queryEvaluationGradeInfo',
    dis: '查询综合评测打分信息',
  },
  {
    code: '',
    key: 'evaluationScoring',
    url: '/projectManage/evaluationScoring',
    dis: '综合评测打分',
  },
  {
    code: '',
    key: 'supplierQueryDemand',
    url: '/projectManage/supplierQueryDemand',
    dis: '查询供应商需求',
  },
  {
    code: '',
    key: 'queryOutsourceCostList',
    url: '/projectManage/queryOutsourceCostList',
    dis: '查询费用列表',
  },
  {
    code: '',
    key: 'globalSearch',
    url: '/projectManage/globalSearch',
    dis: '全局搜索',
  },
  {
    code: '',
    key: 'outsourceCostCalculation',
    url: '/projectManage/outsourceCostCalculation',
    dis: '费用计算',
  },
  {
    code: '',
    key: 'uploadCurriculumVitae',
    url: '/projectManage/uploadCurriculumVitae',
    dis: '简历上传',
  },
  {
    code: '',
    key: 'costCalculationCheck',
    url: '/projectManage/costCalculationCheck',
    dis: '费用计算前校验',
  },
  {
    code: '',
    key: 'outsourceCostExportExcel',
    url: '/projectManage/outsourceCostExportExcel',
    dis: '外包费用导出Excel',
  },
  {
    code: '',
    key: 'queryOutsourceMemberAttendance',
    url: '/projectManage/queryOutsourceMemberAttendance',
    dis: '考勤查询',
  },
  {
    code: '',
    key: 'insertOutsourcePaymentInfo',
    url: '/projectManage/insertOutsourcePaymentInfo',
    dis: '外包人员付款后插入外包付款信息',
  },
  {
    code: '',
    key: 'queryOutsourceRankInfo',
    url: '/projectManage/queryOutsourceRankInfo',
    dis: '人员等级查询',
  },
  {
    code: '',
    key: 'finishOutsourceWork',
    url: '/projectManage/finishOutsourceWork',
    dis: '完成外包事务',
  },
  {
    code: '',
    key: 'queryProjectTracking',
    url: '/projectManage/queryProjectTracking',
    dis: '查询项目跟踪信息',
  },
  {
    code: '',
    key: 'queryProjectNode',
    url: '/projectManage/queryProjectNode',
    dis: '查询项目节点',
  },
  {
    code: '',
    key: 'projectCollect',
    url: '/projectManage/projectCollect',
    dis: '收藏项目',
  },
  {
    code: '',
    key: 'queryCustomQueryCriteria',
    url: '/projectManage/queryCustomQueryCriteria',
    dis: '查询自定义报表里的查询条件',
  },
  {
    code: '',
    key: 'queryMonthlyAssessment',
    url: '/projectManage/queryMonthlyAssessment',
    dis: '月度考核',
  },
  {
    code: '',
    key: 'deleteMonthlyAssessment',
    url: '/projectManage/deleteMonthlyAssessment',
    dis: '删除月度考核',
  },
  {
    code: '',
    key: 'queryCustomReportList',
    url: '/projectManage/queryCustomReportList',
    dis: '查询报表',
  },
  {
    code: '',
    key: 'saveCustomReportSetting',
    url: '/projectManage/saveCustomReportSetting',
    dis: '保存自定义报表配置',
  },
  {
    code: '',
    key: 'queryCustomReport',
    url: '/projectManage/queryCustomReport',
    dis: '自定义报表查询',
  },
  {
    code: '',
    key: 'queryReportOperateRecord',
    url: '/projectManage/queryReportOperateRecord',
    dis: '查询报表历史操作记录',
  },
  {
    code: '',
    key: 'queryProjectStatisticsList',
    url: '/projectManage/queryProjectStatisticsList',
    dis: '查询',
  },
  {
    code: '',
    key: 'queryProjectDynamics',
    url: '/projectManage/queryProjectDynamics',
    dis: '查询首页项目动态信息',
  },
  {
    code: '',
    key: 'queryProjectStatistics',
    url: '/projectManage/queryProjectStatistics',
    dis: '查询项目统计',
  },
  {
    code: '',
    key: 'queryCustomReportContent',
    url: '/projectManage/queryCustomReportContent',
    dis: '查询自定义报告内容',
  },
  {
    code: '',
    key: 'configureCustomReport',
    url: '/projectManage/configureCustomReport',
    dis: '创建自定义报告',
  },
  {
    code: '',
    key: 'editCustomReport',
    url: '/projectManage/editCustomReport',
    dis: '编辑自定义报告内容',
  },
  {
    code: '',
    key: 'completeReport',
    url: '/projectManage/completeReport',
    dis: '报告填写完成',
  },
  {
    code: '',
    key: 'queryApportionsInfo',
    url: '/projectManage/queryApportionsInfo',
    dis: '查询创建单据时所需的分摊信息',
  },
  {
    code: '',
    key: 'queryBudgetStatistics',
    url: '/projectManage/queryBudgetStatistics',
    dis: '预算统计查询',
  },
  {
    code: '',
    key: 'queryPaymentByCode',
    url: '/EKB/v1/queryPaymentByCode',
    dis: '补录付款流程信息时，根据单据编号查询单据信息',
  },
  {
    code: '',
    key: 'supplyPaymentInfo',
    url: '/EKB/v1/supplyPaymentInfo',
    dis: '补录付款流程信息',
  },
  {
    code: '',
    key: 'writeProjectTrackingReport',
    url: '/projectManage/writeProjectTrackingReport',
    dis: '填写项目周报',
  },
  {
    code: '',
    key: 'queryProjectFiles',
    url: '/projectManage/queryProjectFiles',
    dis: '查询项目文档',
  },
  {
    code: '',
    key: 'insertFileDownloadRecord',
    url: '/projectManage/insertFileDownloadRecord',
    dis: '插入项目文档下载记录',
  },
  {
    code: '',
    key: 'finishProject',
    url: '/projectManage/finishProject',
    dis: '完结项目',
  },
  {
    code: '',
    key: 'inviteMemberAgain',
    url: '/projectManage/inviteMemberAgain',
    dis: '再次邀请人员',
  },
  {
    code: '',
    key: 'queryRequisitionData',
    url: '/EKB/v1/queryRequisitionData',
    dis: '查询关联申请信息',
  },
  {
    code: '',
    key: 'queryUnreadInfo',
    url: '/projectManage/queryUnreadInfo',
    dis: '前端轮询获取未读信息数量',
  },
  {
    code: '',
    key: 'insertResumeDownloadRecords',
    url: '/projectManage/insertResumeDownloadRecords',
    dis: '新增简历下载记录',
  },
  {
    code: '',
    key: 'queryResumeDownloadRecords',
    url: '/projectManage/queryResumeDownloadRecords',
    dis: '查询简历下载记录',
  },
  {
    code: '',
    key: 'insertProjectUpdateInfo',
    url: '/projectManage/insertProjectUpdateInfo',
    dis: '新增、修改、删除自研项目升级内容',
  },
  {
    code: '',
    key: 'queryProjectUpdateInfo',
    url: '/projectManage/queryProjectUpdateInfo',
    dis: '查询自研项目升级内容',
  },
  {
    code: '',
    key: 'insertProjectAttendanceRcd',
    url: '/projectManage/insertProjectAttendanceRcd',
    dis: '自研项目考勤登记',
  },
  {
    code: '',
    key: 'queryMemberAttendanceRcd',
    url: '/projectManage/queryMemberAttendanceRcd',
    dis: '查询自研项目考勤记录',
  },
  {
    code: '',
    key: 'insertEvaluateInfo',
    url: '/projectManage/insertEvaluateInfo',
    dis: '新增、修改评估信息',
  },
  {
    code: '',
    key: 'queryEvaluateInfo',
    url: '/projectManage/queryEvaluateInfo',
    dis: '查询迭代项目评估信息',
  },
  {
    code: '',
    key: 'initIterationProjectInfo',
    url: '/projectManage/initIterationProjectInfo',
    dis: '初始化迭代项目信息',
  },
  {
    code: '',
    key: 'queryIteProjPayRcd',
    url: '/projectManage/queryIteProjPayRcd',
    dis: '查询迭代项目付款记录',
  },
  {
    code: '',
    key: 'queryIteProjPayPlan',
    url: '/projectManage/queryIteProjPayPlan',
    dis: '查询迭代项目付款计划',
  },
  {
    code: '',
    key: 'queryContractFlowInfo',
    url: '/projectManage/queryContractFlowInfo',
    dis: '查询合同签署流程',
  },
  {
    code: '',
    key: 'copyCustomReport',
    url: '/projectManage/copyCustomReport',
    dis: '复制自定义报告',
  },
  {
    code: '',
    key: 'insertIteContract',
    url: '/projectManage/insertIteContract',
    dis: '新增、修改迭代合同',
  },
  {
    code: '',
    key: 'queryIteContractInfo',
    url: '/projectManage/queryIteContractInfo',
    dis: '查询迭代合同信息',
  },
  {
    code: '',
    key: 'updateItePayInfo',
    url: '/projectManage/updateItePayInfo',
    dis: '迭代付款后更新迭代付款信息',
  },
  {
    code: '',
    key: 'queryUploadRcd',
    url: '/projectManage/queryUploadRcd',
    dis: '查询简历上传流水',
  },
  {
    code: '',
    key: 'feeCalculation',
    url: '/projectManage/feeCalculation',
    dis: '返回num1对num2的加减乘除保留两位数的结果',
  },
  {
    code: '',
    key: 'querySelfDevProjWHstatistics',
    url: '/projectManage/querySelfDevProjWHstatistics',
    dis: '查询自研项目工时统计',
  },
  {
    code: '',
    key: 'attendanceStatisticExportExcel',
    url: '/projectManage/attendanceStatisticExportExcel',
    dis: '导出自研项目考勤统计',
  },
  {
    code: '',
    key: 'queryLeadApprovalFlow',
    url: '/projectManage/queryLeadApprovalFlow',
    dis: '查询待领导审批流程',
  },
  {
    code: '',
    key: 'updatePaymentContract',
    url: '/projectManage/updatePaymentContract',
    dis: '更新付款关联合同信息',
  },
  {
    code: '',
    key: 'queryIteContractList',
    url: '/projectManage/queryIteContractList',
    dis: '查询迭代合同列表',
  },
  {
    code: '',
    key: 'queryProjectDraft',
    url: '/projectManage/queryProjectDraft',
    dis: '查询项目草稿',
  },
  {
    code: '',
    key: 'relIteContractFlow',
    url: '/projectManage/relIteContractFlow',
    dis: '关联迭代合同',
  },
  {
    code: '',
    key: 'queryIteContractFlow',
    url: '/projectManage/queryIteContractFlow',
    dis: '关联迭代合同签署流程',
  },
  {
    code: '',
    key: 'queryIPRList',
    url: '/projectManage/queryIPRList',
    dis: '查询知识产权列表',
  },
  {
    code: '',
    key: 'queryAwardAndHonorList',
    url: '/projectManage/queryAwardAndHonorList',
    dis: '查询获奖荣誉',
  },
  {
    code: '',
    key: 'editIPRInfo',
    url: '/projectManage/editIPRInfo',
    dis: '编辑知识产权',
  },
  {
    code: '',
    key: 'operateAwardAndHonor',
    url: '/projectManage/operateAwardAndHonor',
    dis: '编辑获奖荣誉',
  },

  {
    code: '',
    key: 'queryXCContractInfo',
    url: '/projectManage/queryXCContractInfo',
    dis: '查询信创合同列表',
  },
  {
    code: '',
    key: 'queryXCContractSubInfo',
    url: '/projectManage/queryXCContractSubInfo',
    dis: '查询信创合同附属信息',
  },
  {
    code: '',
    key: 'operateXCContract',
    url: '/projectManage/operateXCContract',
    dis: '编辑信创合同信息',
  },
  {
    code: '',
    key: 'transferXCContract',
    url: '/projectManage/transferXCContract',
    dis: '信创合同转办',
  },
  {
    code: '',
    key: 'queryProjectXCContract',
    url: '/projectManage/queryProjectXCContract',
    dis: '项目详情里查信创合同',
  },
  {
    code: '',
    key: 'queryIteProjectList',
    url: '/projectManage/queryIteProjectList',
    dis: '查询迭代项目',
  },
  {
    code: '',
    key: 'queryUndoMatters',
    url: '/projectManage/queryUndoMatters',
    dis: '查询未完成事项',
  },
  {
    code: '',
    key: 'queryDocTemplateLibrary',
    url: '/projectManage/queryDocTemplateLibrary',
    dis: '查询文档模板库',
  },
  {
    code: '',
    key: 'editDocTemplate',
    url: '/projectManage/editDocTemplate',
    dis: '编辑文档模板',
  },
  {
    code: '',
    key: 'queryDocType',
    url: '/projectManage/queryDocType',
    dis: '查询文档类型',
  },
  {
    code: '',
    key: 'queryDepartment',
    url: '/EKB/v1/queryDepartment',
    dis: '查询付款流程分摊明细 易快报 部门数据',
  },
  {
    code: '',
    key: 'queryDocTemplate',
    url: '/projectManage/queryDocTemplate',
    dis: '查询文档模板',
  },
];
