export default [
  { code: '', key: 'querySoftwareList', url: '/projectManage/querySoftwareList', dis: '查询软件清单' },
  { code: '', key: 'queryProjectLabel', url: '/projectManage/queryProjectLabel', dis: '查询项目标签' },
  { code: '', key: 'queryOrganizationInfo', url: '/projectManage/queryOrganizationInfo', dis: '查询组织机构' },
  { code: '', key: 'queryBudgetProjects', url: '/projectManage/queryBudgetProjects', dis: '查询预算项目' },
  { code: '', key: 'queryMemberInfo', url: '/projectManage/queryMemberInfo', dis: '查询人员信息' },
  { code: '', key: 'queryMilestoneStageInfo', url: '/projectManage/queryMilestoneStageInfo', dis: '查询里程碑阶段信息' },
  { code: '', key: 'queryMatterUnderMilepost', url: '/projectManage/queryMatterUnderMilepost', dis: '查询里程碑事项信息' },
  { code: '', key: 'queryMilepostInfo', url: '/projectManage/queryMilepostInfo', dis: '查询里程碑信息' },
  { code: '', key: 'creatProject', url: '/projectManage/creatProject', dis: '新建、修改项目' },
  { code: '', key: 'queryProjectDetails', url: '/projectManage/queryProjectDetails', dis: '修改项目时查询项目详细信息' },
  { code: '', key: 'queryStationInfo', url: '/projectManage/queryStationInfo', dis: '查询岗位信息' },
  { code: '', key: 'queryProjectInfoAll', url: '/projectManage/v1/queryProjectInfoAll', dis: '查询所有项目信息' },
  { code: '', key: 'updateHardwareTenderInfo', url: '/projectManage/updateHardwareTenderInfo', dis: '新增、修改硬件项目招标信息' },
  {
    code: '',
    key: 'queryHardwareTendersAndContract',
    url: '/projectManage/queryHardwareTendersAndContract',
    dis: '查询硬件项目招标信息'
  },
  { code: '', key: 'updateHardwareContractInfo', url: '/projectManage/updateHardwareContractInfo', dis: '新增、修改硬件项目招标信息' },
  { code: '', key: 'queryInquiryComparisonInfo', url: '/projectManage/queryInquiryComparisonInfo', dis: '查询硬件项目的询比结果' },
  {
    code: '',
    key: 'updateInquiryComparisonInfo',
    url: '/projectManage/updateInquiryComparisonInfo',
    dis: '新增、修改硬件项目询比结果信息'
  },
  { code: '', key: 'queryHardwareDemandInfo', url: '/projectManage/queryHardwareDemandInfo', dis: '查询硬件项目-需求列表' },
  { code: '', key: 'queryTenderStatisticsInfo', url: '/projectManage/queryTenderStatisticsInfo', dis: '查询硬件项目-标段统计' },
  { code: '', key: 'getDocumentByLiveBos', url: '/livebosService/v1/getDocumentByLiveBos', dis: '查询硬件项目-需求列表' },
  { code: '', key: 'insertSubProjects', url: '/projectManage/insertSubProjects', dis: '集合项目-新增子项目' },
  { code: '', key: 'querySubProjectsInfo', url: '/projectManage/querySubProjectsInfo', dis: '集合项目-查询子项目' },
  { code: '', key: 'queryHWTenderFile', url: '/projectManage/queryHWTenderFile', dis: '硬件项目-查询硬件标段信息的附件' },
];
