export default [
  { code: '506101', key: 'staffDepartmentList', url: '/staffrelationship/v1/staffDepartmentList', dis: '综合通用  管辖部门列表(部门名称、部门经理等)' },
  { code: '506102', key: 'staffTeamList', url: '/staffrelationship/v1/staffTeamList', dis: '综合通用  管辖团队列表(团队名称、团队长等)' },
  { code: '506103', key: 'optionalStaffList', url: '/staffrelationship/v1/optionalStaffList', dis: '综合通用  获取可选人员名单' },
  { code: '506104', key: 'staffTeamMember', url: '/staffrelationship/v1/staffTeamMember', dis: '综合通用  获取团队成员列表' },
  { code: '506105', key: 'loginUserPersonalInfo', url: '/staffrelationship/v1/loginUserPersonalInfo', dis: '综合通用  获取登陆用户人事信息' },
  { code: '506201', key: 'staffList', url: '/staffrelationship/v1/staffList', dis: '人员列表  获取人员列表' },
  { code: '506202', key: 'staffJurisdictionNumber', url: '/staffrelationship/v1/staffJurisdictionNumber', dis: '人员列表  获取管辖人员数' },
  { code: '506203', key: 'staffPersonnelManagementStatus', url: '/staffrelationship/v1/staffPersonnelManagementStatus', dis: '人员列表  获取某人员人事办理状态' },
  { code: '506204', key: 'staffPersonnelManagementStatusExtenDetail', url: '/staffrelationship/v1/staffPersonnelManagementStatusExtenDetail', dis: '人员列表  获取某人员某人事节点详情' },
  { code: '506301', key: 'staffBasicInfo', url: '/staffrelationship/v1/staffBasicInfo', dis: '人员全景  获取人员基础信息' },
  { code: '506302', key: 'staffMoreInfo', url: '/staffrelationship/v1/staffMoreInfo', dis: '人员全景  获取人员详细信息' },
  { code: '506303', key: 'staffRelationshipStatistics', url: '/staffrelationship/v1/staffRelationshipStatistics', dis: '人员全景  获取人员关系统计数据（分类数据+汇总）' },
  { code: '506304', key: 'staffRelationshipDetail', url: '/staffrelationship/v1/staffRelationshipDetail', dis: '人员全景  查询人员客户关系明细' },
  { code: '506305', key: 'staffCusSignDetail', url: '/staffrelationship/v1/staffCusSignDetail', dis: '人员全景  查询人员签约客户明细' },
  { code: '506306', key: 'staffImageDetail', url: '/staffrelationship/v1/staffImageDetail', dis: '人员全景  查询人员影像信息' },
  { code: '506307', key: 'staffContractDetail', url: '/staffrelationship/v1/staffContractDetail', dis: '人员全景  查询人员合同信息' },
  { code: '506308', key: 'staffQualificationDetail', url: '/staffrelationship/v1/staffQualificationDetail', dis: '人员全景  查询人员从业资格信息' },
  { code: '506309', key: 'staffTrainingDetail', url: '/staffrelationship/v1/staffTrainingDetail', dis: '人员全景  查询人员培训信息' },
  { code: '506310', key: 'staffCusActStac', url: '/staffrelationship/v1/staffCusActStac', dis: '人员全景  查询人员客户开户统计' },
  { code: '506311', key: 'staffProSalesStac', url: '/staffrelationship/v1/staffProSalesStac', dis: '人员全景  查询人员产品销售统计' },
  { code: '506312', key: 'staffMonCusNumStac', url: '/staffrelationship/v1/staffMonCusNumStac', dis: '人员全景  查询人员月客户数统计' },
  { code: '506313', key: 'staffRelationNumMonStac', url: '/staffrelationship/v1/staffRelationNumMonStac', dis: '人员全景  查询人员月关系数统计(当月总关系数以及当月新增关系数)' },
  { code: '506314', key: 'staffChagFlow', url: '/staffrelationship/v1/staffChagFlow', dis: '人员全景  查询人员变动流水' },
  { code: '500023', key: 'staffFlowNavigation', url: '/staffrelationship/v1/staffFlowNavigation', dis: '业务导航  查询人员业务流程导航' },
  { code: '500024', key: 'cusContractList', url: '/staffrelationship/v1/cusContractList', dis: '客户全景 获取客户签约流水' },
  { code: '500026', key: 'staffCusNumber', url: '/staffrelationship/v1/staffCusNumber', dis: '客户概况  获取当前人员客户数' },
  { code: '506501', key: 'staffWorklog', url: '/staffrelationship/v1/staffWorklog', dis: '工作日志  获取人员日志列表' },
  { code: '506502', key: 'teamWorklog', url: '/staffrelationship/v1/teamWorklog', dis: '工作日志  获取团队日志列表' },
  { code: '500031', key: 'fillInWorklog', url: '/staffrelationship/v1/fillInWorklog', dis: '工作日志  填写工作日志' },
  { code: '500032', key: 'worklogProjectScope', url: '/staffrelationship/v1/worklogProjectScope', dis: '工作日志  获取日志项目数据范围' },
  { code: '500033', key: 'browseWorklog', url: '/staffrelationship/v1/browseWorklog', dis: '工作日志  记录浏览日志' },
  { code: '506506', key: 'reviewWorklog', url: '/staffrelationship/v1/reviewWorklog', dis: '工作日志  评论日志' },
  { code: '500035', key: 'worklogReviewList', url: '/staffrelationship/v1/worklogReviewList', dis: '工作日志  获取评论列表' },
  { code: '500036', key: 'worklogBrowseList', url: '/staffrelationship/v1/worklogBrowseList', dis: '工作日志  获取浏览列表' },
  { code: '500037', key: 'worklogRemaindNumber', url: '/staffrelationship/v1/worklogRemaindNumber', dis: '工作日志  获取特别提醒数量' },
  { code: '500038', key: 'worklogRemaindList', url: '/staffrelationship/v1/worklogRemaindList', dis: '工作日志  获取特别提醒列表' },
  { code: '500039', key: 'handleWorklogRemaind', url: '/staffrelationship/v1/handleWorklogRemaind', dis: '工作日志  处理特别提醒' },
  { code: '500040', key: 'staffDepartmentList', url: '/staffrelationship/v1/staffDepartmentList', dis: '综合通用  管辖部门列表(部门名称、部门经理)' },
  { code: '500041', key: 'staffTeamList', url: '/staffrelationship/v1/staffTeamList', dis: '综合通用  管辖团队列表(团队名称、团队长)' },
  { code: '500042', key: 'staffTeamMember', url: '/staffrelationship/v1/staffTeamMember', dis: '综合通用  获取团队成员列表' },
  { code: '50000X', key: 'cusRelationInfo', url: '/staffrelationship/v1/cusRelationInfo', dis: '客户全景-客户概览  获取单个客户的关系信息数据' },
  { code: '506601', key: 'staffPerformanceAnalysis', url: '/staffrelationship/v1/staffPerformanceAnalysis', dis: '系统首页  获取人员业绩趋势分析' },
  { code: '506602', key: 'staffCusTradActivityAnalysis', url: '/staffrelationship/v1/staffCusTradActivityAnalysis', dis: '系统首页  获取人员名下客户交易活跃度分析' },
  { code: '506205', key: 'queryStaffTips', url: '/staffrelationship/v1/queryStaffTips', dis: '系统首页  人员模糊搜索' },
  { code: '506208', key: 'staffCusAwkwardness', url: '/staffrelationship/v1/staffCusAwkwardness', dis: '系统首页  重仓股' },
  { code: '506209', key: 'staffCusHotStocks', url: '/staffrelationship/v1/staffCusHotStocks', dis: '系统首页  热门股' },
  { code: '506315', key: 'staffAssetsTransactionTrend', url: '/staffrelationship/v1/staffAssetsTransactionTrend', dis: '人员全景  获取人员资产交易量趋势' },
  { code: '506316', key: 'staffSettlementAccount', url: '/staffrelationship/v1/staffSettlementAccount', dis: '人员全景  查询人员结算账户' },
  { code: '506317', key: 'staffExamSbjInfo', url: '/staffrelationship/v1/staffExamSbjInfo', dis: '获取考试科目信息' },
  { code: '506106', key: 'userConfidentialityData', url: '/staffrelationship/v1/userConfidentialityData', dis: '获取保密协议书内容' },
  { code: '506107', key: 'userCommitmentRecord', url: '/staffrelationship/v1/userCommitmentRecord', dis: '写入用户承诺书签订记录' },
  { code: '506108', key: 'queryStaffCategoryLevel', url: '/staffrelationship/v1/queryStaffCategoryLevel', dis: '查询人员类别即级别关系' },
  { code: 'checkCusPanoramaCompliance', key: 'checkCusPanoramaCompliance', url: '/staffrelationship/v1/checkCusPanoramaCompliance', dis: '登记客户全景合规信息检测' },
  { code: 'cusPanoramaComplianceInfo', key: 'cusPanoramaComplianceInfo', url: '/staffrelationship/v1/cusPanoramaComplianceInfo', dis: '查询客户全景合规信息' },
  { code: '', key: 'queryOtherUsers', url: '/staffrelationship/v1/queryOtherUsers', dis: '查询当前用户的其他用户' },
  { code: '', key: 'uploadProto', url: '/staffrelationship/v1/uploadProto', dis: '上传头像' },
  { code: '506108', key: 'optionalTeamList', url: '/staffrelationship/v1/optionalTeamList', dis: '获取可选团队列表' },
];
